version: '3'

services:
 
 db:
   image: mysql
   restart: always
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: demo@secret
     MYSQL_DATABASE: db_demo
     MYSQL_USER: demo
     MYSQL_PASSWORD: demo

 api:
   build: .
   depends_on:
     - db
   ports:
    - "8080:8080"
   environment:
     - DATABASE_HOST=db
     - DATABASE_PORT=3306
 